package com.banfico.bankingsystem.dto;

import java.math.BigDecimal;

import com.banfico.bankingsystem.entity.Account.AccountType;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AccountRequestDTO
 *
 * Used for POST /api/accounts
 *
 * The accountNumber is generated by the server (not provided by client).
 * The client provides: accountType, initialDeposit, customerId.
 *
 * @NotNull  → value must not be null (use for non-String types)
 * @NotBlank → value must not be null or empty (use for Strings)
 * @DecimalMin → minimum numeric value (here: balance >= 0.00)
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AccountRequestDTO {

    @NotNull(message = "Account type is required")
    private AccountType accountType;

    @NotNull(message = "Initial deposit amount is required")
    @DecimalMin(value = "0.00", message = "Initial deposit cannot be negative")
    private BigDecimal initialDeposit;

    @NotNull(message = "Customer ID is required")
    private Long customerId;
}
