package com.banfico.bankingsystem.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CustomerRequestDTO
 *
 * Used for POST /api/customers and PUT /api/customers/{id}
 *
 * Why a separate Request DTO?
 *   - You never want the client to set "id" or "createdAt" —
 *     those are generated by the server.
 *   - Validation annotations live here, not on the Entity.
 *     Keeps validation logic at the API boundary where it belongs.
 *
 * @NotBlank  → field must not be null AND must have non-whitespace chars
 * @Email     → must be a valid email format (e.g. user@domain.com)
 * @Pattern   → must match the regex (10-digit phone number)
 * @Size      → enforces min/max length
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CustomerRequestDTO {

    @NotBlank(message = "Full name is required")
    @Size(min = 2, max = 100, message = "Full name must be between 2 and 100 characters")
    private String fullName;

    @NotBlank(message = "Email is required")
    @Email(message = "Email must be a valid email address")
    private String email;

    @NotBlank(message = "Phone number is required")
    @Pattern(regexp = "^[0-9]{10}$", message = "Phone must be a 10-digit number")
    private String phone;

    @Size(max = 255, message = "Address must not exceed 255 characters")
    private String address;
}
